// 30 SHAP intro descriptions
export const SHAP_INTRO_TEXTS = [
  "The chart below shows how your selected market factors influenced the latest price forecast. Positive values push the prediction higher, while negative values pull it lower.",
  "Each bar represents a market variable's contribution to the forecast. Green bars indicate upward pressure on gold prices, while red bars signal downward influence.",
  "Here's a breakdown of how each selected factor shaped the forecast. The longer the bar, the stronger the influence on the predicted gold price.",
  "This visualization reveals which factors are driving the forecast up or down. Use it to understand the key forces behind the projected price movement.",
  "The following chart quantifies how each market indicator contributed to the current gold price prediction. Positive impacts suggest bullish pressure; negative impacts suggest bearish pressure.",
  "Explore how your chosen variables interact to shape the forecast. Each bar measures the magnitude and direction of influence on the predicted gold price.",
  "Below you'll see the relative weight of each factor in determining the forecast. Larger bars indicate stronger influence, with color showing the direction.",
  "This analysis breaks down the forecast into individual contributions from each market factor. Together, they explain why the model expects gold to move in this direction.",
  "Understanding what drives the prediction is just as important as the number itself. Each bar shows a factor's net effect on the forecasted gold price.",
  "The drivers chart illustrates which economic forces are pushing gold prices up and which are holding them back, based on your selected variables.",
  "Each factor's contribution is measured independently. Green indicates the factor supports higher gold prices, while red suggests downward pressure.",
  "This chart helps you see beyond the forecast number. It reveals the underlying economic dynamics that shaped the prediction.",
  "Your selected variables each play a role in the forecast. The chart below shows the direction and strength of each factor's influence.",
  "Think of each bar as a vote: green bars vote for higher prices, red bars vote for lower prices. The net result shapes the final forecast.",
  "The influence chart below decomposes the forecast into actionable insights. See which macro factors matter most for gold's near-term trajectory.",
  "Market factors rarely move in isolation. This chart shows how each selected variable independently contributes to the overall gold price forecast.",
  "The bars below represent each factor's isolated impact on the prediction. Use this to identify which economic trends matter most right now.",
  "Every forecast tells a story. The chart below reveals which chapters — inflation, rates, commodities — are writing gold's next price move.",
  "Below is a factor-by-factor breakdown of the forecast. Positive contributions push gold higher; negative contributions act as headwinds.",
  "This explainability chart connects the dots between macroeconomic trends and the gold price outlook, showing each variable's individual impact.",
  "Wondering why gold is forecast to move this way? The chart below attributes the prediction to specific market forces you've selected.",
  "Each bar quantifies a single factor's pull on the forecast. Together, they paint a complete picture of the forces shaping gold's trajectory.",
  "The magnitude of each bar reflects how sensitive the gold forecast is to that particular market variable. Longer bars deserve more attention.",
  "This breakdown shows the net effect of each predictor on the gold outlook. It helps separate noise from the signals that truly matter.",
  "Gold prices respond to a web of economic forces. The chart below untangles that web, showing each thread's individual contribution.",
  "Use this chart to assess which macro drivers are currently most relevant to gold. The direction and size of each bar tell the story.",
  "The forecast isn't a black box. Below, each factor's contribution is laid out transparently so you can evaluate the reasoning yourself.",
  "From inflation to commodities, each factor exerts its own force on gold. See how they stack up in the contribution chart below.",
  "The explainability view below shows the 'why' behind the 'what'. Each bar is a window into the economic logic of the forecast.",
  "Data-driven insights start here. The chart maps each selected variable's effect on the prediction, giving you clarity on what's moving gold.",
];

// 30 Key takeaway texts
export const SHAP_TAKEAWAY_TEXTS = [
  "Inflation expectations and geopolitical risk had the strongest positive influence on this forecast, while rising interest rates and equity market strength partially offset the upward momentum.",
  "The current forecast is primarily driven by inflation dynamics and precious metals correlation, with interest rate headwinds providing a counterbalance.",
  "Gold's bullish outlook stems from strong inflationary signals, though bond yield pressures and a resilient stock market temper the upside.",
  "Safe-haven demand and inflation hedging are the dominant themes, outweighing the drag from higher rates and a stronger equity market.",
  "The balance of forces leans bullish: inflation and commodity trends support gold, while monetary tightening creates measured resistance.",
  "Key upward drivers include persistent inflation and correlated precious metal strength. The primary headwinds come from rising yields and equity outperformance.",
  "This forecast reflects a tug-of-war between inflationary tailwinds and interest rate headwinds, with inflation currently winning.",
  "Macro conditions favor gold: inflation remains elevated, commodities are trending higher, and despite rate increases, real yields remain supportive.",
  "The strongest signal in this forecast is inflation pressure, which historically correlates with sustained gold demand from institutional investors.",
  "While higher bond yields and equity gains create friction, the net effect of all factors still points to a positive gold price trajectory.",
  "Inflation-driven demand continues to be the primary engine behind gold's forecast, supported by broad commodity price momentum.",
  "The forecast suggests gold will benefit from an inflationary environment, even as central banks attempt to cool the economy with higher rates.",
  "Multiple factors align to support a moderately bullish outlook, with inflation and silver co-movement leading the charge.",
  "Interest rate increases are the most significant headwind, but they're outweighed by the combined force of inflation, silver, and copper trends.",
  "The data points to sustained gold strength. Inflationary pressure is the dominant factor, reinforced by positive signals from the broader commodity complex.",
  "Gold remains well-supported by macro fundamentals. The forecast reflects a market where inflation fears outweigh confidence in monetary policy normalization.",
  "The interplay between rates and inflation remains the central story. Currently, inflation's bullish pull on gold exceeds the bearish drag from higher yields.",
  "Commodity prices across the board are reinforcing gold's upward trajectory, while traditional headwinds from bonds and equities provide only partial offset.",
  "This forecast is shaped by a classic late-cycle dynamic: inflation persists, commodities rally, and gold benefits as a store of value.",
  "The strongest bearish factor — interest rates — is not enough to overcome the combined bullish impact of inflation, silver, and industrial metals.",
  "Investor sentiment appears to favor hard assets. The forecast captures this through elevated contributions from inflation and precious metal correlation.",
  "Bond yields are rising but haven't reached levels that would meaningfully deter gold investment. Meanwhile, inflation continues to fuel demand.",
  "The forecast leans positive, driven by a convergence of inflationary signals and commodity strength that more than compensates for rate-driven headwinds.",
  "Gold's appeal as an inflation hedge is the story of this forecast. Secondary support comes from correlated movements in silver and copper.",
  "The macro environment presents a mixed but net-positive picture for gold, with inflation and commodity tailwinds dominating over financial tightening pressures.",
  "Higher rates and equity resilience are notable headwinds, yet the scale of inflationary impact keeps the forecast firmly in bullish territory.",
  "This prediction captures a market in transition: traditional safe-haven demand meets modern inflationary pressures, resulting in a positive gold outlook.",
  "The data suggests investors should watch inflation metrics closely — they remain the single largest driver of gold's projected price movement.",
  "Cross-asset signals from silver and copper reinforce the bullish gold thesis, adding confidence to the inflation-driven forecast.",
  "The overall picture is constructive for gold. While no single factor dominates overwhelmingly, the cumulative effect of bullish drivers outpaces bearish ones.",
];
